FROM nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04

# Установка Python и зависимостей
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 python3-pip python3-dev \
        gcc g++ git wget \
        libgl1-mesa-glx libglib2.0-0 && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./src/indexer/ .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "indexer.py"]