FROM python:3.12-slim

# Установка Python и зависимостей
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc g++ python3-dev zlib1g-dev

WORKDIR /app

COPY ./src/analyzer/ ./analyzer/
COPY ./src/bot/ ./bot/

RUN pip install --no-cache-dir -r ./bot/requirements.txt

CMD ["python", "analyzer/analyzer.py"]