FROM python:3.12-slim

# Установка Python и зависимостей
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc g++ python3-dev zlib1g-dev

WORKDIR /app

COPY ./src/tester/ .
COPY ./knowledge_config/golden_questions.json ./tests/golden_questions.json
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "tester.py"]